Avoid function calls to NativeEndian
vishvananda/netlink pull request #393
Opened 2018-10-04 15:25 UTC by corny

2018-11-20 00:31 UTC, aboch commented
May you add some more information about what this change is trying to achieve. Thanks.

2018-11-20 22:35 UTC, dmke commented on nl/nl_unspecified.go
> +func native binary.ByteOrder {
This seems like a mistake. Search and replace too greedy?

2018-11-20 23:03 UTC, dmke commented
@aboch: This PR consists of 3 changes:

1. Rename `native` to `nativeOrder`. (I guess to better communicate intent)
2. Move endian detection from `NativeEndian()` to program startup and degrade `NativeEndian()` to a simple getter.
3. Replace internal `NativeEndian()` calls with the cached `nativeOrder` value. This removes one function call from the stack.

2020-09-14 15:00 UTC, vishvananda commented
I'm ok with this approach in general if you want to rebase it, although I'm not sure the savings are significant enough to make a large difference.

2020-10-20 09:14 UTC, corny commented
@vishvananda I rebased my changes on top of the current master. Please review them.

2020-10-22 13:10 UTC, dmke requested changes
LGTM, but I'd like to see a bit of documentation to *clearly* state the intended purpose (see comment below).

2020-10-22 13:10 UTC, dmke commented on nl/nl_linux.go
> +var nativeEndian = func() binary.ByteOrder {
I'd add a comment, stating something along the lines of "native byte order as determined at program startup" and "assuming it doesn't change at runtime".

2021-05-08 16:22 UTC, closed without merging