Add socket diagnosis for UDP
vishvananda/netlink pull request #927
Opened 2023-11-15 21:27 UTC by srebhan

This PR adds netlink socket diagnosis support for UDP and implements parsing of the `INET_DIAG_MEMINFO` extension data.

2023-11-27 18:38 UTC, aboch commented
@srebhan This project follows a "1 commit per PR" approach.
Either squash the commits into one or open a separate PR for each, if each brings a distinct fix/functionality.

2023-11-30 15:47 UTC, srebhan commented
@aboch will squash the commits then. Thought you squash them on merge...

2023-12-04 18:11 UTC, aboch commented on socket_linux.go
> +			// default:
If it makes sense to handle the default case, please uncomment it. If not, please remove it.

2023-12-04 18:12 UTC, aboch commented on socket_linux.go
> +			// default:
same here

2023-12-04 18:15 UTC, aboch commented
Can you see if possible to add or extend existing UT to cover this functionality?

2024-01-03 07:57 UTC, srebhan commented
@aboch any update on this PR? Anything I can do to make the merge happen?

2024-01-08 17:46 UTC, aboch requested changes

2024-01-08 17:46 UTC, aboch commented on go.mod
> +	github.com/stretchr/testify v1.8.4
This is not needed for the feature added by this PR.
Can you please remove?

2024-01-08 17:46 UTC, aboch commented on socket_test.go
> +	require.NoError(t, err)
No need for this for this feature addition.
Existing testing code is readable just fine IMO.

2024-01-25 16:57 UTC, aboch commented
please squash the two commits into one

2024-01-26 10:53 UTC, srebhan commented
@aboch done.

2024-01-26 17:08 UTC, merged